const categories = {
    "Incident Response": [
        "incident",
        "response",
        "forensics",
        "dfir",
        "investigation",
        "triage",
        "analysis",
        "compromise",
        "breach",
        "threat"
    ],
    "S3 Auditing": [
        "s3",
        "bucket",
        "permissions",
        "auditing",
        "storage",
        "object",
        "access",
        "aws s3",
        "buckets"
    ],
    "Compliance": [
        "compliance",
        "security",
        "cis",
        "pci",
        "frameworks",
        "benchmark",
        "governance",
        "regulations",
        "standards",
        "audit",
        "policy"
    ],
    "IAM Tools": [
        "iam",
        "identity",
        "role",
        "permissions",
        "policy",
        "users",
        "groups",
        "access",
        "authentication",
        "authorization"
    ],
    "Cloud Monitoring": [
        "monitoring",
        "alerts",
        "metrics",
        "logs",
        "cloudwatch",
        "activity",
        "dashboard",
        "tracking",
        "notification",
        "telemetry",
        "analytics"
    ],
    "Static Analysis": [
        "scan",
        "checkov",
        "analysis",
        "terraform",
        "cloudformation",
        "configuration",
        "vulnerability",
        "misconfiguration",
        "static",
        "lint",
        "inspection"
    ],
    "Secrets Management": [
        "secret",
        "keys",
        "token",
        "vault",
        "credential",
        "encryption",
        "key rotation",
        "secrets",
        "leaks",
        "passwords"
    ],
    "Cloud Infrastructure": [
        "infrastructure",
        "provisioning",
        "terraform",
        "cloudformation",
        "deployment",
        "automation",
        "iaas",
        "orchestration",
        "infrastructure-as-code"
    ],
    "Threat Detection": [
        "threat",
        "detection",
        "malware",
        "abuse",
        "anomaly",
        "attack",
        "red team",
        "recon",
        "security monitoring",
        "exploitation"
    ],
    "Data Security": [
        "data",
        "encryption",
        "storage",
        "leakage",
        "detection",
        "security",
        "classification",
        "sensitive",
        "backup",
        "protection"
    ],
    "Penetration Testing": [
        "pentest",
        "testing",
        "exploitation",
        "red team",
        "recon",
        "simulation",
        "ethical hacking",
        "vulnerabilities",
        "attack",
        "audit"
    ],
    "Container Security": [
        "container",
        "docker",
        "kubernetes",
        "orchestration",
        "image scanning",
        "runtime",
        "containerization",
        "pod",
        "cluster",
        "microservices"
    ],
    "Serverless Security": [
        "serverless",
        "lambda",
        "faas",
        "cloud functions",
        "event-driven",
        "runtime security",
        "functions",
        "aws lambda",
        "api gateway",
        "trigger"
    ],
    "Cloud Cost Management": [
        "cost",
        "optimization",
        "billing",
        "savings",
        "usage",
        "resources",
        "expenses",
        "accounting",
        "spend",
        "estimation"
    ],
    "Policy Management": [
        "policy",
        "rules",
        "compliance",
        "configuration",
        "benchmark",
        "security group",
        "firewall",
        "permissions",
        "policy enforcement",
        "controls"
    ],
    "API Security": [
        "api",
        "gateway",
        "rest",
        "web services",
        "soap",
        "authentication",
        "authorization",
        "api calls",
        "throttling",
        "rate limiting"
    ]
};

module.exports = { categories };
