name: Fetch, Build, and Deploy to S3

on:
  schedule:
    # Run every day at midnight UTC
    - cron: "0 0 * * *"
  workflow_dispatch: # Allow manual triggering

jobs:
  fetch-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm install

    # Step 4: Run the fetchRepoData script
    # - name: Fetch repository data
    #   run: node utils/fetchData/fetchRepoData.cjs
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Step 5: Build the project
    - name: Build the project
      run: npm run build

    # Step 6: Deploy to S3 using OIDC
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::010526279859:role/gh-action-fetch-build-deploy
        aws-region: us-east-1

    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@v0.5.1
      with:
        args: --acl public-read --delete
        bucket: ${{ secrets.S3_BUCKET_NAME }}
        source_dir: ./dist
